# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 1.0

build:
  os: windows-11
  tools:
    python: "3.11"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/src

formats:
    - pdf

python:
    install:
    - requirements: docs/requirements.txt
